#!/bin/sh

set -e

if [ "$#" -ne 1 ]; then
    echo "usage: $0 config_dir"
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "error: no config in \"$1\""
    exit 1
fi

ln -snf ${1#*/} ${1%%/*}/active_config
find ${1%%/*} -name '*.less' -exec touch {} +
